# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

inhibit_all_warnings!

target 'whoparty' do

pod 'MBProgressHUD', '0.9'
pod 'pop', '~> 1.0'
pod 'FlatUIKit'
pod 'JTCalendar', '~> 1.0'
pod 'SPGooglePlacesAutocomplete'
pod 'SLExpandableTableView', '1.3.1'


end

target 'whopartyTests' do

end

