# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

inhibit_all_warnings!

target 'whoparty' do

pod 'AFNetworking', '~> 2.5'
pod 'MBProgressHUD', '~> 0.9'
pod 'NUI'
pod 'pop', '~> 1.0'
pod 'FlatUIKit'

end

target 'whopartyTests' do

end

